### ISSUE TITLE
Problem of generator

### ISSUE THREAD

**Issue by PierreJobic** [sjenni/LearningToSpotArtifacts#1]
The 'high level distortion' announced by the article is not satisfying according to this code.
Here are two images made by this code after the last epoch:

Input images -> AutoEncoder Output: 
[https://drive.google.com/open?id=1iwQ6sPcx1IrPqBLhKdFHxVUxjaPW-Dx7](url)

Input images -> Encoder/Damage/RepairDecoder Output
[https://drive.google.com/open?id=1nC4NpApaCzGOEHBnD8tP0cvFdlFCuU9f](url)

**Comment by sjenni** [comment]
Hi Pierre,
I'm sorry for the late reply. There was an issue with the activation functions of the autoencoder not being consistent between pre-training and unsupervised training. It should be fixed now.
